### ISSUE TITLE
Unable to read device, recurrence of #613

### ISSUE THREAD

**Issue by wohali** [SpenceKonde/megaTinyCore#871]
Hi Spence,

I am also trying to read out a device and failing in exactly the same way as #613. However, I have literally just installed your tooling from the Board Manager, so perhaps the bug has not been squashed?

```
joant@amos:~/.arduino15/packages/megaTinyCore/hardware/megaavr/2.6.4/tools$ python3 ./prog.py -d attiny412 -wd 1 --fuses_print -f read.hex -a read -rc 512 -u /dev/ttyUSB0
SerialUPDI
UPDI programming for Arduino using a serial adapter
Based on pymcuprog, with significant modifications
By Quentin Bolsee and Spence Konde
Version 1.2.3 - Jan 2022
Using serial port /dev/ttyUSB0 at 115200 baud.
Reading in chunks not longer than 512 bytes (-rc).
Delaying next op after each page write command by 1.0ms (-wd).
Target: attiny412
Action: read
File: read.hex
Pinging device...
Ping response: 1E9223
Reading...
Traceback (most recent call last):
  File "/home/joant/.arduino15/packages/megaTinyCore/hardware/megaavr/2.6.4/tools/./prog.py", line 285, in <module>
    main()
  File "/home/joant/.arduino15/packages/megaTinyCore/hardware/megaavr/2.6.4/tools/./prog.py", line 128, in main
    return_code = pymcuprog_basic(args, fuses_dict)
  File "/home/joant/.arduino15/packages/megaTinyCore/hardware/megaavr/2.6.4/tools/./prog.py", line 238, in pymcuprog_basic
    run_pymcu_action(pymcu._action_read, backend,
  File "/home/joant/.arduino15/packages/megaTinyCore/hardware/megaavr/2.6.4/tools/./prog.py", line 138, in run_pymcu_action
    status = func(backend, *args, args_pymcu)
  File "/home/joant/.arduino15/packages/megaTinyCore/hardware/megaavr/2.6.4/tools/libs/pymcuprog/pymcuprog_main.py", line 201, in _action_read
    result = backend.read_memory(args.memory, args.offset, args.bytes, args.max_read_chunk)
AttributeError: 'Namespace' object has no attribute 'max_read_chunk'
```

The version of pymcuprog installed matches what I see here in the repo, but it seems quite old:

```
joant@amos:~/.arduino15/packages/megaTinyCore/hardware/megaavr/2.6.4/tools/libs/pymcuprog$ more version.py
""" This file was generated when pymcuprog was built """
VERSION = '3.6.4.86'
COMMIT_ID = '6224623cfc85c5e7cb6b1df8419b72c338c223f9'
BUILD_DATE = '2020-11-09 14:49:15 +0000'
```

I am unable to find a versioning information inside of `~/.arduino15/packages/megaTinyCore/hardware/megaavr/2.6.4/tools/libs/pymcuprog/serialupdi`, unfortunately. 

The Arduino Board Manager tells me version 2.6.4 of megaTinyCore is installed. I am running Arduino IDE v1.8.13.

FYI, I tried both leaving `-rc` off (initially) and then adding the default value explicitly on the CLI - neither worked.

**Comment by SpenceKonde** [comment]
should be fixed now
